from django.db import models

# Create your models here.
class Resume(models.Model):
    name=models.CharField(max_length=122)
    about=models.TextField()
    age=models.CharField(max_length=3)
    email=models.CharField(max_length=122)
    phone=models.CharField(max_length=12)
    skill1=models.CharField(max_length=122)
    skill2=models.CharField(max_length=122)
    skill3=models.CharField(max_length=122)
    skill4=models.CharField(max_length=122)
    skill5=models.CharField(max_length=122)
    degree1=models.CharField(max_length=122)
    college1=models.CharField(max_length=122)
    year1=models.CharField(max_length=5)
    degree2=models.CharField(max_length=122)
    college2=models.CharField(max_length=122)
    year2=models.CharField(max_length=5)
    degree3=models.CharField(max_length=122)
    college3=models.CharField(max_length=122)
    year3=models.CharField(max_length=5)
    lang1=models.CharField(max_length=122)
    lang2=models.CharField(max_length=122)
    lang3=models.CharField(max_length=122)
    project1=models.CharField(max_length=122)
    durat1=models.CharField(max_length=122)
    desc1=models.TextField()
    project2=models.CharField(max_length=122)
    durat2=models.CharField(max_length=122)
    desc2=models.TextField()
    company1=models.CharField(max_length=122)
    post1=models.CharField(max_length=122)
    duration1=models.CharField(max_length=122)
    lin11=models.TextField()
    company2=models.CharField(max_length=122)
    post2=models.CharField(max_length=122)
    duration2=models.CharField(max_length=122)
    lin21=models.TextField()
    ach1=models.CharField(max_length=122)
    ach2=models.CharField(max_length=122)
    ach3=models.CharField(max_length=122)

    def __str__(self):
        return self.name